export const SEARCH_FETCHING = "SEARCHFETCHING";
export const SEARCH_TV_FETCH = "SEARCHTVFETCH";
export const SEARCH_MOVIE_FETCH = "SEARCHMOVIEFETCH";
export const SEARCH_FETCH_ERROR = "SEARCHFETCHERROR";
